/**
 * 硅藻属名表 (diatom genera) —— 自动生成，请勿手工编辑。
 *
 * 由 `support/sync_diatom_vocab.py` 从 `straditize_core/ocr/data/diatom_genera.json`
 * 生成；后者由 `support/harvest_diatom_genera.py` 采集自中国科学院烟台海岸带研究所
 * 硅藻检索表 (plant.yic.ac.cn)：
 *   - 内陆/淡水检索表 151 属（Round 1990，译自 Kociolek et al. 2003）
 *   - 海洋检索表 114 属（金德祥 1982）
 *
 * 与后端 `PollenDictionary` 使用同一份词表，避免两侧纠正结果不一致。
 */

export const DIATOM_GENERA: string[] = [
  "Aalafia",
  "Acanthoceras",
  "Achnanthes",
  "Achnanthidium",
  "Actinella",
  "Actinocyclus",
  "Actinoptychus",
  "Amphicampa",
  "Amphipleura",
  "Amphiprora",
  "Amphora",
  "Amphorotia",
  "Anaulus",
  "Aneumastus",
  "Anomoeoneis",
  "Anorthoneis",
  "Arachnoidiscus",
  "Asterionella",
  "Asterolampra",
  "Asteromphalus",
  "Attheya",
  "Aulacodiscus",
  "Aulacoseira",
  "Auliscus",
  "Auricula",
  "Bacillaria",
  "Bacteriastrum",
  "Bellerochea",
  "Berkeleya",
  "Biddulphia",
  "Biremis",
  "Boreozonacola",
  "Brachysira",
  "Brevilinea",
  "Brevisira",
  "Caloneis",
  "Campylodiscus",
  "Campyloneis",
  "Capartogramma",
  "Cavinula",
  "Cerataulina",
  "Cerataulus",
  "Ceratoneis",
  "Chaetoceros",
  "Chamaepinnularia",
  "Cistula",
  "Climacodium",
  "Climacosphenia",
  "Cocconeis",
  "Corethron",
  "Coscinodiscus",
  "Coscinosira",
  "Cosmioneis",
  "Craticula",
  "Ctenophora",
  "Cyclostephanos",
  "Cyclotella",
  "Cyclotubicoalitus",
  "Cylindrotheca",
  "Cymatopleura",
  "Cymatosira",
  "Cymbella",
  "Cymbellafalsa",
  "Cymbellonitzschia",
  "Cymbopleura",
  "Dactyliosolen",
  "Decussata",
  "Delicata",
  "Denticula",
  "Desmogonium",
  "Diadesmis",
  "Diatoma",
  "Diatomella",
  "Didymosphenia",
  "Diploneis",
  "Discostella",
  "Distrionella",
  "Ditylum",
  "Ellerbeckia",
  "Encyonema",
  "Encyonopsis",
  "Endictya",
  "Entomoneis",
  "Envekadea",
  "Eolimna",
  "Epithemia",
  "Eucampia",
  "Eucocconeis",
  "Eunotia",
  "Fallacia",
  "Fistulifera",
  "Fragilaria",
  "Fragilariforma",
  "Frickea",
  "Frustulia",
  "Geissleria",
  "Gomphocymbella",
  "Gomphoneis",
  "Gomphonema",
  "Gomphonitzschia",
  "Gomphosphenia",
  "Gossleriella",
  "Grammatophora",
  "Guinardia",
  "Gyrosigma",
  "Halamphora",
  "Handmannia",
  "Hannara",
  "Hantzschia",
  "Haslea",
  "Hemiaulus",
  "Hemidiscus",
  "Hippodonta",
  "Humidophila",
  "Hyalodiscus",
  "Hydrosera",
  "Hygropetra",
  "Isthmia",
  "Karayevia",
  "Kobayasiella",
  "Kolbesia",
  "Lauderia",
  "Lemnicola",
  "Leptocylindrus",
  "Leudugeria",
  "Licmophora",
  "Luticola",
  "Mastogloia",
  "Mastogonia",
  "Mayamaea",
  "Melosira",
  "Meridion",
  "Mesodictyon",
  "Microcostatus",
  "Muelleria",
  "Navicula",
  "Navicymbula",
  "Neidiomorpha",
  "Neidiopsis",
  "Neidium",
  "Nitzschia",
  "Nupela",
  "Orthoseira",
  "Oxyneis",
  "Parlibellus",
  "Peronia",
  "Phaeodactylum",
  "Pinnularia",
  "Placoneis",
  "Plagiogramma",
  "Plagiotropis",
  "Planktoniella",
  "Planothidium",
  "Playaensis",
  "Pleurosigma",
  "Pleurosira",
  "Pliocaenicus",
  "Podocystis",
  "Podosira",
  "Prestauroneis",
  "Proschkinia",
  "Psammodictyon",
  "Psammothidium",
  "Pseudo-Eunotia",
  "Pseudo-Nitzschia",
  "Pseudostaurosira",
  "Pulchella",
  "Punctastriata",
  "Pyxidicula",
  "Raphidodiscus",
  "Reimeria",
  "Rexlowea",
  "Rhabdonema",
  "Rhaphoneis",
  "Rhizosolenia",
  "Rhoicosphenia",
  "Rhopalodia",
  "Roperia",
  "Rossithidium",
  "Rutilaria",
  "Schroederella",
  "Scoliopleura",
  "Sellaphora",
  "Semiorbis",
  "Sieminskia",
  "Simonsenia",
  "Skeletonema",
  "Spicaticribra",
  "Stauroforma",
  "Stauroneis",
  "Staurophora",
  "Staurosira",
  "Staurosirella",
  "Stenopterobia",
  "Stephanocostis",
  "Stephanodiscus",
  "Stephanopyxis",
  "Stictocyclus",
  "Stictodiscus",
  "Stoermeria",
  "Strelnikoviella",
  "Streptotheca",
  "Striatella",
  "Surirella",
  "Synedra",
  "Tabellaria",
  "Tabularia",
  "Terpsinoe",
  "Tertiarius",
  "Tetracyclus",
  "Thalassionema",
  "Thalassiosira",
  "Thalassiothrix",
  "Trachyneis",
  "Tropidoneis",
  "Tryblionella",
  "Tryblioptychus",
  "Tubularia",
  "Ulnaria",
  "Urosolenia",
  "Williamsella",
];

export const DIATOM_SOURCE_ALIASES: Record<string, string> = {
  "Bacteriastru": "Bacteriastrum",
  "Discostlla": "Discostella",
  "Endictyca": "Endictya",
  "Eunoita": "Eunotia",
  "Gomphoeymbella": "Gomphocymbella",
  "Leudugera": "Leudugeria",
  "Meridiom": "Meridion",
  "Neidiun": "Neidium",
  "Rhabdomema": "Rhabdonema",
  "Rhoiconeis": "Rhoicosphenia",
  "Soliopleura": "Scoliopleura",
  "Tetratella": "Tetracyclus",
  "Thalasiosira": "Thalassiosira",
};

export const DIATOM_GENERA_SOURCE = {
  "inland": "http://plant.yic.ac.cn/microalgae/diatom/key/inland.php",
  "marine": "http://plant.yic.ac.cn/microalgae/diatom/key/marine.php",
  "inland_classification": "Round (1990), translated from Kociolek et al. (2003); 152 genera",
  "marine_classification": "金德祥 (1982), amended from 金德祥 (1965) and 杨树民/董树刚 (2006); 114 genera",
  "harvested_by": "support/harvest_diatom_genera.py"
} as const;
